name: Continuous Integration and Continuous Deployment

on:
  push:
    branches: 
    - "master"

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore APIEnem.API
    - name: Build
      run: dotnet build APIEnem.API

  tests:
    name: Domain Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: dotnet test APIEnem.DomainTests

  deploy: 
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: tests
    environment: Produção
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.email "otaviovb.developer@gmail.com"
          git config --global user.name "OtavioVB"
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apienem"
          heroku_email: "otaviovb.developer@gmail.com"
          justlogin: true
          
          appdir: APIEnem.API
          usedocker: true   
          
      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app apienem

      - name: "Releases the container"
        run: heroku container:release web --app apienem
