name: Continuous Integration and Continuous Deployment

on:
  push:
    branches: 
    - "*"

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.302'

  tests:
    name: Domain Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: dotnet test APIEnem.DomainTests

  deploy: 
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: tests
    environment: Produção
    steps:
      - uses: actions/checkout@v1
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apienem"
          heroku_email: "otaviovb.developer@gmail.com"
          appdir: APIEnem.Infra
          usedocker: true 
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apienem"
          heroku_email: "otaviovb.developer@gmail.com"
          appdir: APIEnem.Domain
          usedocker: true 
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apienem"
          heroku_email: "otaviovb.developer@gmail.com"
          appdir: APIEnem.API
          usedocker: true   