name: CI

on: [pull_request]

jobs:
  build:
    name: Debug Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.302'

  tests:
    name: Tests
    runs-on: ubuntu-latest
    environment: Desenvolvimento
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: echo Tests