name: Continuous Integration and Continuous Deployment

on:
  push:
    branches: 
    - "master"

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.302'
        
  deploy: 
    name: Deploy Project
    runs-on: ubuntu-latest
    environment: Produção
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.email "otaviovb.developer@gmail.com"
          git config --global user.name "OtavioVB"
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apienem"
          heroku_email: "otaviovb.developer@gmail.com"
          appdir: APIEnem.API 
          usedocker: true
